package xlab.world.xlab.utils.support

object IntentPassName {
    const val ACCESS_TOKEN = "ACCESS_TOKEN"
    const val IS_COME_PRELOAD_ACTIVITY = "IS_COME_PRELOAD_ACTIVITY"
    const val USER_LOGIN_DATA = "USER_LOGIN_DATA"
    const val USER_EMAIL = "USER_EMAIL"
    const val PAGE_TITLE = "PAGE_TITLE"
    const val WEB_URL = "WEB_URL"
    const val WEB_ZOOM_CONTROL = "WEB_ZOOM_CONTROL"
    const val POST_ID = "POST_ID"
    const val GO_COMMENT = "GO_COMMENT"
    const val USER_ID = "USER_ID"
    const val WITH_CIRCLE_OVERLAY = "WITH_CIRCLE_OVERLAY"
    const val PET_NO = "PET_NO"
    const val PET_TYPE = "PET_TYPE"
    const val PET_TOTAL = "PET_TOTAL"
    const val IMAGE_URL = "IMAGE_URL"
    const val BREED_INDEX = "BREED_INDEX"
    const val SEARCH_TEXT = "SEARCH_TEXT"
    const val SEARCH_CODE = "SEARCH_CODE"
    const val IMAGE_PATH_LIST = "IMAGE_PATH_LIST"
    const val YOUTUBE_VIDEO_ID = "YOUTUBE_VIDEO_ID"
    const val SELECTED_USED_GOODS = "SELECTED_USED_GOODS"
    const val GOODS_CODE = "GOODS_CODE"
    const val DELIVER_NO = "DELIVER_NO"
    const val GOODS_NAME = "GOODS_NAME"
    const val GOODS_ORIGIN = "GOODS_ORIGIN"
    const val GOODS_MAKER = "GOODS_MAKER"
    const val INTENT_FROM = "INTENT_FROM"
    const val SNO_LIST = "SNO_LIST"
    const val ORDER_NO = "ORDER_NO"
}